# kubernetes/configmap.yaml
# Non-secret configuration for slack-export-viewer.
# All values here correspond to the SEV_* environment variables documented at
# https://github.com/hfaran/slack-export-viewer
apiVersion: v1
kind: ConfigMap
metadata:
  name: slack-viewer-config
  namespace: slack-viewer
data:
  SEV_IP: "0.0.0.0"
  SEV_PORT: "5000"
  SEV_ARCHIVE: "/data/export.zip"
  SEV_NO_BROWSER: "true"
  # Uncomment / modify as required:
  # SEV_SHOW_DMS: "true"
  # SEV_CHANNELS: "general,random"
  # SEV_HIDE_CHANNELS: "alerts"
  # SEV_SKIP_CHANNEL_MEMBER_CHANGE: "true"
  # SEV_THREAD_NOTE: "true"
